### ISSUE TITLE
Can we make BBE title and url consistent

### ISSUE THREAD

**Issue by anupama-pathirage** [ballerina-platform/ballerina-distribution#3461]
**Description:**
Most of the BBEs have deviated a lot and sometimes it doesn't make sense or give a different meaning. 

Also the run command displayed in the BBE is similar to the URL name. So it is very important to have a meaningful and consistent file name.

Check all the places. 

E.g.

<img width="1354" alt="image" src="https://user-images.githubusercontent.com/16300038/202539980-5f5af842-6b56-4dde-9958-664421f54b26.png">

In some BBEs, URL, title and run command file name are totally different.

Refer https://pre-prod.ballerina.io/learn/by-example/http-header-param/

**Comment by chamil321** [comment]
<img width="1500" alt="Screenshot 2022-11-24 at 20 31 00" src="https://user-images.githubusercontent.com/8381003/203815237-7c90ae81-e436-4dbc-ad13-21b61eb88f59.png">
Fixed all HTTP BBEs as above

https://github.com/ballerina-platform/ballerina-distribution/pull/3539/files#diff-6f4e938742c0d5b8a5677ead32fba6083c45d897e6fd21e1d5a9055affba2832R1

**Comment by anupama-pathirage** [comment]
Reopening as we can still see the differences. Check for non HTTP BBEs as well.

E.g. : https://ballerina.io/learn/by-example/http-basic-rest-service/

URL : http-basic-rest-service
File name : http_basic_rest_api.bal

<img width="1488" alt="image" src="https://user-images.githubusercontent.com/16300038/205969749-b7f33029-3e2d-4304-8a11-d6df3f4d1e5b.png">

**Comment by chamil321** [comment]
> Reopening as we can still see the differences. Check for non HTTP BBEs as well.
> 
> E.g. : https://ballerina.io/learn/by-example/http-basic-rest-service/
> 
> URL : http-basic-rest-service File name : http_basic_rest_api.bal
> 
> <img alt="image" width="1488" src="https://user-images.githubusercontent.com/16300038/205969749-b7f33029-3e2d-4304-8a11-d6df3f4d1e5b.png">

Fixed via e5e3d2db6fff6a954ca9b122aff39bc4b7800594

**Comment by chamil321** [comment]
Fixed via https://github.com/ballerina-platform/ballerina-distribution/commit/e5e3d2db6fff6a954ca9b122aff39bc4b7800594
